DELIMITER // 
CREATE PROCEDURE `RENTUPDATE`()
BEGIN
DECLARE ch_done INT DEFAULT 0;
DECLARE U_LATEFEE INTEGER;
DECLARE U_DUEDATE DATE;
DECLARE U_RENTAMT INTEGER;
DECLARE U_STATUS VARCHAR(10);
DECLARE U_RENTID INTEGER;
DECLARE U_RENT CURSOR FOR 
SELECT R.RENT_ID, R.RENT_FEE, R.DUE_DATE, R.LATE_FEE, S.R_STATUS
FROM RENT AS R, RENT_STATUS AS S
WHERE R.RENT_ID = S.RENT_ID AND R.DUE_DATE = CURDATE()
FOR UPDATE;
DECLARE EXIT HANDLER FOR NOT FOUND SET ch_done = 1;
OPEN U_RENT;
LOOP
	FETCH U_RENT INTO U_RENTID, U_RENTAMT, U_DUEDATE, U_LATEFEE, U_STATUS;
	IF ( U_STATUS != 'Unpaid' ) THEN
		SET U_LATEFEE = U_LATEFEE;
	ELSE
		SET U_LATEFEE = U_RENTAMT + U_LATEFEE + ((5 * U_RENTAMT)/100) ;
	END IF;
	UPDATE RENT_STATUS AS RS SET RS.R_STATUS = 'Unpaid' WHERE RS.R_STATUS = U_STATUS AND RS.RENT_ID = U_RENTID;
	UPDATE RENT AS R SET LATE_FEE = U_LATEFEE, DUE_DATE = (CURDATE() + INTERVAL 31 day ) 
	WHERE DUE_DATE = U_DUEDATE AND  R.RENT_ID = U_RENTID ; 
END LOOP;
CLOSE U_RENT;
END; // 
DELIMITER ;  

CALL RENTUPDATE();