CREATE TABLE TENANT_BACKUP(
FNAME VARCHAR(25),
LNAME VARCHAR(15),
T_ID INTEGER AUTO_INCREMENT,
PH_NO VARCHAR(12),
EMAIL VARCHAR(30),
GENDER CHAR,
DOB DATE,
OCCUPATION VARCHAR(30),
ROOM_NO INTEGER,
PSWD VARCHAR(25),
PRIMARY KEY(T_ID),
FOREIGN KEY(ROOM_NO) REFERENCES APARTMENT(ROOM_NO) ON DELETE SET NULL);


DELIMITER //
CREATE TRIGGER TRG_TENANT 
BEFORE DELETE ON TENANT 
FOR EACH ROW
BEGIN
INSERT INTO TENANT_BACKUP(FNAME, LNAME,T_ID, PH_NO, EMAIL, GENDER, DOB ,OCCUPATION, ROOM_NO) VALUES (OLD.FNAME, OLD.LNAME, OLD.T_ID, OLD.PH_NO, OLD.EMAIL, OLD.GENDER, OLD.DOB ,OLD.OCCUPATION, OLD.ROOM_NO);
END ; //
DELIMITER ;